require "user.plugins"
require('impatient')
vim.notify = require("notify")
require "user.keymaps"
require "user.options"
require "user.colorscheme"
require "user.whichkey"
require "user.treesitter"
require "user.better_escape"
require "user.lualine"
require "user.neoscroll"
require "user.cmp"
require "user.lsp_config"
require "user.lua_snippets"
require "user.bufferline"
require "user.neotree"
require "user.dap_servers"
require "user.dap_ui"
