-- require "user.plugins"
require "user.lazy"
require "user.colorscheme"
vim.notify = require("notify")
require "user.keymaps"
require "user.options"
require "user.whichkey"
require "user.treesitter"
require "user.better_escape"
require "user.neoscroll"
require "user.cmp"
require "user.lsp_config"
require "user.lua_snippets"
require "user.bufferline"
require "user.neotree"
require "user.dap_servers"
require "user.dap_ui"
require "user.git"
require("flutter-tools").setup {}
