require "user.options"
require "user.lazy"
require "user.colorscheme"
require "user.keymaps"
require "user.whichkey"
require "user.treesitter"
require "user.better_escape"
require "user.cmp"
require "user.lua_snippets"
require "user.lsp_config"
require "user.bufferline"
require "user.mini"
require "user.dap_servers"
require "user.dap_ui"
require "user.git"
require "user.autocmd"

vim.g.vimtex_view_general_viewer = 'zathura'
