#!/bin/sh

# Ensure bspwm starts as the window manager
sxhkd &

# Monitors Name
monitor1="eDP-1"
monitor2="DP-1"

# How much monitors are available
total_monitors=$(xrandr --listmonitors | awk '/Monitors:/ {print $2}')
notify-send "Total Monitor" "$total_monitors monitor(s) available"

# Polybar
killall -q polybar

# Setting BSPWM depending on how much monitors are available
if [ "$total_monitors" -eq 1 ]; then
    bspc monitor "$monitor1" -d 1 2 3 4 5 6 7 0
    polybar bar1 -c $HOME/.config/bspwm/polybar/config1.ini &
elif [ "$total_monitors" -eq 2 ]; then
    xrandr --output "$monitor2" --auto --above "$monitor1"
    bspc monitor "$monitor1" -d 0
    bspc monitor "$monitor2" -d 1 2 3 4 5 6 7
    polybar bar2 -c $HOME/.config/bspwm/polybar/config2.ini &
    bspc config -m "#monitor1" top_padding 0
fi


# Follow the mouse when changing workspace or focus
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

# Set initial focus
bspc monitor -f 1

# Set default desktop layout
bspc desktop -l tiled

# Set wallpaper
feh --bg-fill $HOME/.config/bspwm/assets/colorfulAI.png &
# feh --bg-fill $HOME/.config/bspwm/assets/via_lactea.jpg &

# Set mouse cursor
$xsetroot -cursor_name left_ptr &

# Start compositor
#$picom &

# { Rules

bspc rule -a '*' state=tiled

# send to workspace
bspc rule -a ticktick -o desktop=^4
bspc rule -a google-chrome -o desktop=^2

# floating client
bspc rule -a megasync state=floating

# Rules }

# Open Apps
betterlockscreen $HOME/.config/bspwm/assets/colorfulAI.png
blueman-applet &
megasync &
nm-applet &
ticktick &

# Look and Feel
bspc config window_gap            5
bspc config border_width          1
bspc config normal_border_color   "#333333"
bspc config active_border_color   "#333333"
bspc config focused_border_color  "#FE5600"
